<<<<<<< HEAD
spring.application.name=dmn-2025
esto.bachelor.name=Dï¿½veloppement Multimï¿½dia Numï¿½rique
esto.bachelor.promotion=2025-2026
esto.bachelor.cordonator=Pr Kodad Mohcine
=======
spring.application.name=dmn-2019
esto.bachelor.name=Développement Multimédia Numérique
esto.bachelor.promotion=2019-2020
esto.bachelor.cordonator=Pr Azizi Med
>>>>>>> develop
